### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by knoxcard2** [shipshapecode/tether#351]
```
[!] Error: Cannot find module 'autoprefixer'
Require stack:
- /mnt/c/indospace.io/www/static/tether/rollup.config.js
- /root/.nvm/versions/node/v12.11.0/lib/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'autoprefixer'
Require stack:
- /mnt/c/indospace.io/www/static/tether/rollup.config.js
- /root/.nvm/versions/node/v12.11.0/lib/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/c/indospace.io/www/static/tether/rollup.config.js:7:36)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.require.extensions..js (/root/.nvm/versions/node/v12.11.0/lib/node_modules/rollup/dist/bin/rollup:838:24)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rwwagner90** [comment]
@knoxcard2 I am not sure what you are trying to do here. Could you please elaborate?

**Comment by knoxcard2** [comment]
figured it out..
